# Automatically generated by Colaboratory.
# https://colab.research.google.com/github/thiziolkowski/thiziolkowski/blob/main/Python_ANOTA%C3%87%C3%95ES.ipynb

# PYTHON

# IMPORTANTE! As informações utilizadas a seguir foram extraidas do **site w3schools** para uso em consultas sobre a linguagem.

# - Comentários  #comentários

# - Comentários
'''
  Comentários  em várias linhas
'''
# - A contagem de posições inicia em ZERO 0-1-2-3...

# - Pular linha Print('\n')

# - VARIÁVEIS

# - Usar aspas SIMPLES ou DUPLAS em texto ex: print("Hello")
# - VARIÁVEIS - Não é necessário declarar o tipo da variável

'''
  x = "Hello World"	>> str
  x = 20	>> int
  x = 20.5 >> float
  x = 1j	>> complex
  x = ["apple", "banana", "cherry"]	>> list
  x = ("apple", "banana", "cherry") >> tuple
  x = range(6)	>> range
  x = {"name" : "John", "age" : 36}	>> dict
  x = {"apple", "banana", "cherry"}	>> set
  x = frozenset({"apple", "banana", "cherry"})	>> frozenset
  x = True >> bool
  x = b"Hello" >> bytes
  x = bytearray(5) >> bytearray
  x = memoryview(bytes(5)) >> memoryview
  x = None	>> NoneType negrito
'''

print ("Hello world!")

nome = 'Thiago'
idade = 34
print(nome, idade)

x, y, z = "Orange", "Banana", "Cherry"
print(x)

x = y = z = 'Orange'
print(x)
print(y)

x = 5
y = 10
print(x + y)

a = """Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."""
print(a)

# Descobrindo o tipo da variável
x = 'Thiago'
print(type(x))

# Trabalhando com string

# Concatenando string
a = "Hello"
b = "World"
c = a + " " + b
print(c)

# Descobrindo o tamanho de uma string
a = "Hello, World!"
print(len(a))

# Contando a quantidade de vezes que uma sequencia de caracteres aparece
txt = "I love apples, apple are my favorite fruit"
x = txt.count("apple", 0, 24) #limitar o intervalo de busca se necessário
print(x)

# Descobrindo posição de um texto
txt = "Hello, welcome to my world."
x = txt.find("welcome")
print(x)

#Limitando o campo de busca
txt = "Hello, welcome to my world."
x = txt.find("e", 5, 10)
print(x)

# Removendo espaços em branco (inicio ou fim da palavra/texto)
a = "   Hello, World! "
print(a.strip())

# Modificando o tamanho do texto para MAIUSCULA, minuscula (É importante em validações de nomes por exemplo)
a = "Hello, World!"
print(a.upper())

a = "Hello, World!"
print(a.lower())

# Extraindo posições específicas de um texto
a = "Hello, World!"
print(a[1])

# Extraindo caracteres de um intervalo (Quando não informar um numero, ele ira do inicio ao fim)
b = "Hello, World!"
print(b[2:5])

b = "Hello, World!"
print(b[:5])

# Dividindo uma String em Multiplas Strings** (Informar o caractere de separação)
a = "Hello, World!"
print(a.split(","))

# Looping para visualização
for x in "banana":
  print(x)

# Consultando uma palavra ou texto dentro de uma string
txt = "The best things in life are free!"
print("free" in txt)

txt = "The best things in life are free!"
print("expensive" not in txt)

# Substituindo caracteres
a = "Hello, World!"
print(a.replace("Hello", "Bom dia"))

## FUNÇÃO- Randon

# Gera um número aleatório entre 1 e 10
import random
print(random.randrange(1, 10))

## FUNÇÃO - IF
txt = "The best things in life are free!"
if "free" in txt:
  print("Yes, 'free' is present.")

txt = "The best things in life are free!"
if "expensive" not in txt:
  print("No, 'expensive' is NOT present.")

# INPUT DE DADOS PELO USUÁRIO
name = input('Digite seu nome: ')
print('\n')
print('Olá ',name)

# VERIFICAÇÃO SIMPLES DE IDADE COM IF (CALCULO DE IDADE É COM DATA E NÃO MANUALMENTE)
print('\n')
nome = input('Digite seu nome: ')
idade = int(input('Digite sua idade: '))

print('\n')

if idade < 18:
    print('Site proibido para menores de 18')
else:
    print('Vamos lá', nome)

print('\n')
